---
# tasks file for install-keepalived
- name: Install keepalived
  become: true
  ansible.builtin.apt:
    update_cache: yes
    name: keepalived
    state: present
  notify: Start-keepalived

- name: Copy keepalived config
  become: true
  ansible.builtin.template:
    src: keepalived.cfg.j2
    dest: /etc/keepalived/keepalived.conf
  notify: Restart-keepalived

# - name: Start Keepalived Systemd Service.
#   become: true
#   ansible.builtin.service:
#     name: keepalived
#     state: started
#     enabled: yes
#     daemon_reload: yes
